version: '3'

services:
    web:
        build: web

    php:
        build: php
        ports:
         - "80:80"
        volumes:
         - ./web:/var/www/html/
        networks:
         - default

    mysql:
        build: mysql
        ports:
         - "3306:3306"
        depends_on:
         - php