version: '3'

services:
    web:
        build: web

    proxy:
        build: proxy
        ports:
         - "80:80"

    php:
        build: php
        ports:
         - "9000:9000"

    mysql:
        build: mysql
        ports:
         - "3306:3306"
        depends_on:
         - php