FROM php:7.2-apache

RUN sudo apt-get install software-properties-common -y
RUN sudo add-apt-repository ppa:ondrej/php
RUN sudo apt install php7.2 libapache2-mod-php7.2 php7.2-common php7.2-mbstring php7.2-xmlrpc php7.2-soap php7.2-gd php7.2-xml php7.2-intl php7.2-mysql php7.2-cli php7.2-zip php7.2-curl -y