FROM php:latest-apache

#ENV MYSQL_HOST dbtugas5.cenzylrufou4.us-east-1.rds.amazonaws.com
#ENV MYSQL_ROOT_PASSWORD root
#ENV MYSQL_DATABASE db_tugas5
#ENV MYSQL_USER eusebia
#ENV MYSQL_PASSWORD tugas5_eusebia